//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson11Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nmpk22cntt4Lesson11Entities : DbContext
    {
        public Nmpk22cntt4Lesson11Entities()
            : base("name=Nmpk22cntt4Lesson11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NmpCategory> NmpCategory { get; set; }
        public virtual DbSet<NmpProduct> NmpProduct { get; set; }
    }
}
