//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NmpCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NmpCategory()
        {
            this.NmpProduct = new HashSet<NmpProduct>();
        }
       [Display (Name ="Mã danh m?c")]
        public int NmpID { get; set; }

        [Display(Name = "Tên danh m?c")]
        public string NmpCateName { get; set; }

        [Display(Name = "Tr?ng thái")]
        public Nullable<bool> NmpStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NmpProduct> NmpProduct { get; set; }
    }
}
