//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmpProduct
    {
        public string NmpId2210900141 { get; set; }
        public string NmpProName { get; set; }
        public Nullable<int> NmpQty { get; set; }
        public Nullable<double> NmpPrice { get; set; }
        public Nullable<int> NmpCateId { get; set; }
        public Nullable<bool> NmpActive { get; set; }
    
        public virtual NmpCategory NmpCategory { get; set; }
    }
}
