//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmpAccount
    {
        public int NmpID { get; set; }
        public string NmpUserName { get; set; }
        public string NmpPassword { get; set; }
        public string NmpFullName { get; set; }
        public string NmpEmail { get; set; }
        public string NmpPhone { get; set; }
        public Nullable<bool> NmpActive { get; set; }
    }
}
