//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpOnTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NguyenMinhPhuongOnTapEntities : DbContext
    {
        public NguyenMinhPhuongOnTapEntities()
            : base("name=NguyenMinhPhuongOnTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nmp_Account> Nmp_Account { get; set; }
        public virtual DbSet<Nmp_Sach> Nmp_Sach { get; set; }
        public virtual DbSet<NmpTacGia> NmpTacGia { get; set; }
    }
}
