//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpOnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nmp_Account
    {
        public string Nmp_ID { get; set; }
        public string Nmp_UserName { get; set; }
        public string Nmp_PassWord { get; set; }
        public string Nmp_FullName { get; set; }
        public string Nmp_Email { get; set; }
        public Nullable<int> Nmp_Phone { get; set; }
        public Nullable<bool> Nmp_Active { get; set; }
    }
}
