//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpOnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmpTacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NmpTacGia()
        {
            this.Nmp_Sach = new HashSet<Nmp_Sach>();
        }
    
        public string Nmp_MaTG { get; set; }
        public string Nmp_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nmp_Sach> Nmp_Sach { get; set; }
    }
}
