//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmpKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NmpKhoa()
        {
            this.NmpSinhViens = new HashSet<NmpSinhVien>();
        }
    
        public string NmpMaKhoa { get; set; }
        public string NmpTenKhoa { get; set; }
        public Nullable<bool> NmpTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NmpSinhVien> NmpSinhViens { get; set; }
    }
}
