//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmpLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmpSinhVien
    {
        public string NmpMaSV { get; set; }
        public string NmpHoSV { get; set; }
        public string NmpTenSV { get; set; }
        public Nullable<bool> NmpPhai { get; set; }
        public string NmpEmail { get; set; }
        public string NmpPhone { get; set; }
        public string NmpMaKhoa { get; set; }
    
        public virtual NmpKhoa NmpKhoa { get; set; }
    }
}
