//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmplesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NMP_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NMP_TACGIA()
        {
            this.NMP_SACH = new HashSet<NMP_SACH>();
        }
    
        public string Nmp_MaTG { get; set; }
        public string NmpTenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NMP_SACH> NMP_SACH { get; set; }
    }
}
